name: 自动部署为 GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: 1、读取仓库内容
        uses: actions/checkout@v4

      - name: 2、设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3、安装 pnpm
        run: npm install -g pnpm

      - name: 4、安装依赖
        run: pnpm install --frozen-lockfile

      - name: 5、构建项目（使用 .env.github）
        run: pnpm run build:github

      - name: 6、部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true
